/*

 */
package view_Ana_Priscilla;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model_Ana_Priscilla.Votacao;

/**
 *
 * @author anapriscilla
 */
public class Tela_Registro_Ana_Priscilla extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Candidato_Ana_Priscilla
     */
    public Tela_Registro_Ana_Priscilla() {
        initComponents();
        initComplementos();
    }
    
    /*Para centralizar a tela */
    public void initComplementos() {
        this.setLocationRelativeTo(null);
        
    }
    
    /*Chamando a proxima janela*/
    Tela_Votacao_Ana_Priscilla votacao = new Tela_Votacao_Ana_Priscilla();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeCandidato1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomeCandidato2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomeCandidato3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(42, 79, 150));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(42, 79, 150));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTRAR CANDIDATO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 79, 150));
        jLabel2.setText("URnas - Sistema de Votação - RESGISTRAR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("1º Candidato:");

        nomeCandidato1.setBackground(new java.awt.Color(255, 255, 255));
        nomeCandidato1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeCandidato1KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("2º Candidato:");

        nomeCandidato2.setBackground(new java.awt.Color(255, 255, 255));
        nomeCandidato2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeCandidato2KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("3º Candidato:");

        nomeCandidato3.setBackground(new java.awt.Color(255, 255, 255));
        nomeCandidato3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeCandidato3KeyTyped(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\vote 1 (1).png")); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeCandidato2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addComponent(nomeCandidato3)
                            .addComponent(nomeCandidato1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCandidato2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCandidato3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //Tratamento de exceção para campos vazios ou repetidos
         if(nomeCandidato1.getText().equals("") || nomeCandidato2.getText().equals("")|| nomeCandidato3.getText().equals("")
            ||nomeCandidato1.getText().toUpperCase().equals(nomeCandidato2.getText().toUpperCase())||nomeCandidato1.getText().toUpperCase().equals(nomeCandidato3.getText().toUpperCase())
            ||nomeCandidato2.getText().toUpperCase().equals(nomeCandidato1.getText().toUpperCase())||nomeCandidato2.getText().toUpperCase().equals(nomeCandidato3.getText().toUpperCase())
            ||nomeCandidato3.getText().toUpperCase().equals(nomeCandidato1.getText().toUpperCase())||nomeCandidato3.getText().toUpperCase().equals(nomeCandidato2.getText().toUpperCase())
          ){ 
             JOptionPane.showMessageDialog(this, " | ERRO | CAMPO VAZIO OU CANDIDATO REPETIDO");  
         } else {
                // Pegando os dados digitados pelo usuário
                if(!nomeCandidato1.getText().isEmpty() && !nomeCandidato2.getText().isEmpty() 
                   && !nomeCandidato3.getText().isEmpty()){
                    if(votacao==null){
                        votacao = new Tela_Votacao_Ana_Priscilla();
                        votacao.setLocationRelativeTo(null);
                        votacao.setVisible(true);
                        votacao.setResizable(false);

                    } else {
                        votacao.setLocationRelativeTo(null);
                        votacao.setVisible(true);
                        votacao.setResizable(false);
                    }

                    votacao.enviaPalavra(this, nomeCandidato1.getText());
                    votacao.enviaPalavra2(this, nomeCandidato2.getText());
                    votacao.enviaPalavra3(this, nomeCandidato3.getText());
                    this.dispose();  
  
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //Tratamento de exceção para não deixar digitar inteiros no lugar de String
    private void nomeCandidato1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCandidato1KeyTyped

        char candidato1=evt.getKeyChar();
        //Aqui verificamos se o que foi digitado é um número, um backspace ou um delete. Se for, consumimos o evento, ou seja, o jTextField não receberá o valor digitado
        if((Character.isDigit(candidato1) || (candidato1==KeyEvent.VK_BACK_SPACE) || candidato1==KeyEvent.VK_DELETE)){
        evt.consume();
        JOptionPane.showMessageDialog(this, " | Erro | NÃO ACEITA NÚMEROS SOMENTE LETRAS");
        }                  
       
    }//GEN-LAST:event_nomeCandidato1KeyTyped

    private void nomeCandidato2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCandidato2KeyTyped

        char candidato2=evt.getKeyChar();
        
        if((Character.isDigit(candidato2) || (candidato2==KeyEvent.VK_BACK_SPACE) || candidato2==KeyEvent.VK_DELETE)){
        evt.consume();
        JOptionPane.showMessageDialog(this, " | Erro | NÃO ACEITA NÚMEROS SOMENTE LETRAS");
        }                 
       
    }//GEN-LAST:event_nomeCandidato2KeyTyped

    private void nomeCandidato3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCandidato3KeyTyped

        char candidato3=evt.getKeyChar();
        
        if((Character.isDigit(candidato3) || (candidato3==KeyEvent.VK_BACK_SPACE) || candidato3==KeyEvent.VK_DELETE)){
        evt.consume();
        JOptionPane.showMessageDialog(this, " | Erro | NÃO ACEITA NÚMEROS SOMENTE LETRAS");
        }   
    }//GEN-LAST:event_nomeCandidato3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Registro_Ana_Priscilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Registro_Ana_Priscilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Registro_Ana_Priscilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Registro_Ana_Priscilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Registro_Ana_Priscilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeCandidato1;
    private javax.swing.JTextField nomeCandidato2;
    private javax.swing.JTextField nomeCandidato3;
    // End of variables declaration//GEN-END:variables
}
